#!/bin/bash
# List all files and directories including hidden ones
# Sort by alphanumeric order with directories at the beginning
# Append a trailing slash to directory names
# Print result with commas separating the entries

{
    echo -n './, ../, '
    ls -a | grep -E '^\.' | sort -t/ -k2,2 -k1,1 | sed 's|[^/]*$|&/|'
    ls -a | grep -vE '^\.' | sort -t/ -k1,1
} | paste -sd ',' - | sed 's|/,,|,,|g'
