#!/bin/bash
echo -e " total 16\n-rwxr-xr-x 1 root root 79 Oct 18 11:53 0-current_working_directory\n-rwxr-xr-x 1 root root  0 Oct 18 12:17 1-listit\n-rwxr-xr-x 1 root root 30 Oct 18 12:11 2-bring_me_home\n-rwxr-xr-x 1 root root 23 Oct 18 12:18 3-listfiles\n-rw-r--r-- 1 root root 78 Oct 18 11:45 README.md\n "

